apiVersion: apps/v1
kind: Deployment
metadata:
  name: booking-api-deplo
  namespace: taller-dos
  labels:
    app: booking-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: booking-service
  template:
    metadata:
      labels:
        app: booking-service
    spec:
      containers:
      - name: booking-service
        image: booking-service:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 9050
---
apiVersion: v1
kind: Service
metadata:
  name: booking-service
  namespace: taller-dos
  labels:
    app: booking-service
spec:
  type: NodePort
  selector:
    app: booking-service
  ports:
    - protocol: TCP
      port: 9050
      targetPort: 9050
