apiVersion: apps/v1
kind: Deployment
metadata:
  name: movie-api-deplo
  namespace: taller-dos
  labels:
    app: movie-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: movie-service
  template:
    metadata:
      labels:
        app: movie-service
    spec:
      containers:
      - name: movie-service
        image: movie-service:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 9070
---
apiVersion: v1
kind: Service
metadata:
  name: movie-service
  namespace: taller-dos
  labels:
    app: movie-service
spec:
  type: NodePort
  selector:
    app: movie-service
  ports:
    - protocol: TCP
      port: 9070
      targetPort: 9070
