apiVersion: apps/v1
kind: Deployment
metadata:
  name: showtime-api-deplo
  namespace: taller-dos
  labels:
    app: showtime-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: showtime-service
  template:
    metadata:
      labels:
        app: showtime-service
    spec:
      containers:
      - name: showtime-service
        image: showtime-service:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 9080
---
apiVersion: v1
kind: Service
metadata:
  name: showtime-service
  namespace: taller-dos
  labels:
    app: showtime-service
spec:
  type: NodePort
  selector:
    app: showtime-service
  ports:
    - protocol: TCP
      port: 9080
      targetPort: 9080
