apiVersion: apps/v1
kind: Deployment
metadata:
  name: admin-api-deplo
  namespace: taller-dos
  labels:
    app: admin-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: admin-service
  template:
    metadata:
      labels:
        app: admin-service
    spec:
      containers:
      - name: admin-service
        image: admin-service:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 9020
---
apiVersion: v1
kind: Service
metadata:
  name: admin-service-svc
  namespace: taller-dos
  labels:
    app: admin-service
spec:
  type: NodePort
  selector:
    app: admin-service
  ports:
    - protocol: TCP
      port: 9020
      targetPort: 9020
