apiVersion: apps/v1
kind: Deployment
metadata:
  name: config-service-api-deplo
  namespace: taller-dos
  labels:
    app: config-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: config-service
  template:
    metadata:
      labels:
        app: config-service
    spec:
      containers:
      - name: config-service
        image: config-service:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 9000
---
apiVersion: v1
kind: Service
metadata:
  name: config-service-svc
  namespace: taller-dos
  labels:
    app: config-service
spec:
  type: NodePort
  selector:
    app: config-service
  ports:
    - protocol: TCP
      port: 9000
      targetPort: 9000
