apiVersion: apps/v1
kind: Deployment
metadata:
  name: eureka-api-deplo
  namespace: taller-dos
  labels:
    app: eureka-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eureka-service
  template:
    metadata:
      labels:
        app: eureka-service
    spec:
      containers:
      - name: eureka-service
        image: eureka-service:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 9010
---
apiVersion: v1
kind: Service
metadata:
  name: eureka-service-svc
  namespace: taller-dos
  labels:
    app: eureka-service
spec:
  type: NodePort
  selector:
    app: eureka-service
  ports:
    - protocol: TCP
      port: 9010
      targetPort: 9010
